### ISSUE TITLE
Provide `dotnet new` template for Worker

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#11]
Provide a [custom `dotnet new`](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates) template which configures a Worker with minimal requirements.

The template should be calles `arcus-servicebus-queue` and `arcus-servicebus-topic`.

## Features in the template

- [x] TCP Health Probes
- [x] Register `ICachedSecretProvider` as dependency
- [x] Registration of message pump which is using empty message handler
  - By default, use `ISecretProvider` for getting connection string
- [x] Empty message handler

## Good reads

- https://rehansaeed.com/custom-project-templates-using-dotnet-new/

**Comment by stijnmoreels** [comment]
@tomkerkhove , question.
I've come up with a maintainable approach to test the message pump in generated projects from the message pump project template (ServiceBus Queue). But I'm not sure of a few things:

* A message pump should be present in the resulting project without any extra project options?
* Of what other project options do you think? Because if they all relate to the message pump, I'll move some of the functionality at a higher level. Not sure in what direction this template will grow, that's why I ask.

**Comment by tomkerkhove** [comment]
As discussed, the template should:
1. Create a message pump (ie. `OrderMessagePump`) with a temporary message type that logs a message
2. Register the secret provider
3. Register health checks
4. Register message pump with temporary message type

**Comment by tomkerkhove** [comment]
@stijnmoreels This is finished, right?! 🎉

**Comment by stijnmoreels** [comment]
> @stijnmoreels This is finished, right?! 🎉

We've now got a template for the Service Bus Queue; we may need one to for the Service Bus Topic.
Not many work, but I'ld keep this open till that's done. OK?

**Comment by tomkerkhove** [comment]
Sounds good to me!
