### ISSUE TITLE
ISecretProvider: Runtime error after migration to .Net 6 Function App v4 migration: 

### ISSUE THREAD

**Issue by HelenaCoppieters** [arcus-azure/arcus.templates#667]
**Describe the bug**
On line 78 of Startup.cs in the migrated Function App project (  var secretProvider = prov.GetRequiredService<ISecretProvider>(); )
This line gives the following Runtime error:
"A host error has occurred during startup operation '13a2764b-6ed9-43a4-8e87-b5f478889a7b'.
[2022-08-30T07:45:48.910Z] Microsoft.Extensions.DependencyInjection: Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Diagnostics.HostFileLoggerProvider'."
![image](https://user-images.githubusercontent.com/86767115/187382232-7a5d9fc0-8258-4474-8657-518c756e33f9.png)

**To Reproduce**
- Clone branch lab-part-Net6 from the Github repo https://github.com/Codit/aca-paas/
- Set the following project as startup: https://github.com/Codit/aca-paas/tree/lab-part5-Net6/src/Codit.Training.PaaS.Codito.RentalFunctions
- Build code (compiles without errors)
- Run the function app locally

**Expected behavior**
No Runtimes error after migration of function app

**Additional context**
 - Version .Net 6 Function App v4 Arcus packages latest versions

**Comment by stijnmoreels** [comment]
Thx for the issue, Helena,
Saw this line: https://github.com/Codit/aca-paas/blob/a467e87dcbbd5f02ea16b1d7742ed3fbb2e7dbf2/src/Codit.Training.PaaS.Codito.RentalFunctions/Startup.cs#L77 which is a very bad practice in terms of dependency injection. This will destabilize the entire dependency container (singletons will be created twice, instead of once, for example).
I imagine this not being something pure Arcus as the failure is about setting up logger (which the secret store uses), and is this point still in 'building' mode as where in the startup code.

**Comment by stijnmoreels** [comment]
Better would be to inject the secret store into one of your dependent services.

**Comment by HelenaCoppieters** [comment]
In this article on the MS Docs site, there's an example of a correct and bad usage of GetRequiredService when you want to scope as a singleton:
https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#scoped-service-as-singleton

**Comment by pim-simons** [comment]
Regarding the uefa code, this was indeed used there but that implementation is a bit old. In the new fifa project we have moved away from that code 👍🏻  see for example https://github.com/Codit/fifa-worldcup-championship-predictions/blob/main/src/functions/api.users.get/function/Startup.cs

**Comment by HelenaCoppieters** [comment]
@Pim, is it not advised to use the connectionstring instead of the instrumentation key for the example you gave:  [fifa-worldcup](https://github.com/Codit/fifa-worldcup-championship-predictions/blob/main/src/functions/api.users.get/function/Startup.cs)


I mean, should this  `var instrumentationKey = appConfig.GetValue<string>("APPINSIGHTS_INSTRUMENTATIONKEY");`' 
be better replaced by `   string connectionString = context.Configuration.GetValue<string>("APPLICATIONINSIGHTS_CONNECTION_STRING");`
 ?

Should this connectionString be preferrable kept in a Key vault, or is it sufficient keep it in e.g. for Web Api config connectionstring settings?

**Comment by pim-simons** [comment]
@HelenaCoppieters that is a good one 👍🏻 something I will have to update. Thanks for the review 😉 
I think the safest place to store the connectionstring is indeed in KeyVault.

**Comment by stijnmoreels** [comment]
> In this article on the MS Docs site, there's an example of a correct and bad usage of GetRequiredService when you want to scope as a singleton: https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#scoped-service-as-singleton

Yes, that is correct, but not used here. Creating first a scope, for scoped services is not related to this topic, as the pending `ServiceCollection` is used to create a service provider.
I'm not aware of common Codit practices, and I remember pointing this stuff out to Tom too (which he changed afterwards).

To get back on the issue: could you change the code and make it so that you only use the service provider within an implementation factory within a service registration w/o building the provider yourself?

**Comment by stijnmoreels** [comment]
> @HelenaCoppieters that is a good one 👍🏻 something I will have to update. Thanks for the review 😉 I think the safest place to store the connectionstring is indeed in KeyVault.

We have an example written out to store the connection string in the Arcus secret store: https://github.com/arcus-azure/arcus.observability/blob/master/docs/preview/03-Features/sinks/azure-application-insights.md#q-where-can-i-initialize-the-logger-in-an-aspnet-core-application-or-other-hosted-service

**Comment by stijnmoreels** [comment]
@HelenaCoppieters , the Azure Functions in-process variant is a very lightweight version which doesn't include much extension points. The only extension point that's available is setting up the application configuration and setting up application services. Nowhere is the possibility to add functionality outside those two (think about the lack of middleware, for example).
This also means that the logging should be configured from the application services. This means that the connection string should already be retrieved from the secret store (which is also a registered service) beforehand. This will cause an endless loop of 'secret store requesting logger', 'logger requesting secret store'. That's also the reason why we had to move the code outside the hosting functionality in the example. We can do that in isolated Azure Functions, but not in in-process Azure Functions due to the lack of extension points.
Hope this clarifies things.

**Comment by HelenaCoppieters** [comment]
@stijnmoreels , Thank you for the explanation, because I didn't manage to find good solution for the in-process function app and I didn't understand why..

**Comment by HelenaCoppieters** [comment]
By the way, If you would like some help for extending to the Arcus documentation and keeping it up-to-date, I would be happy to contribute.

**Comment by stijnmoreels** [comment]
> By the way, If you would like some help for extending to the Arcus documentation and keeping it up-to-date, I would be happy to contribute.

By all means! Thank you! ❤️ 
If you find a contradiction or something vague, feel free to propose an alternate version in a PR!

**Comment by pim-simons** [comment]
> @pim, is it not advised to use the connectionstring instead of the instrumentation key for the example you gave: [fifa-worldcup](https://github.com/Codit/fifa-worldcup-championship-predictions/blob/main/src/functions/api.users.get/function/Startup.cs?rgh-link-date=2022-08-30T14%3A06%3A59Z)
> 
> I mean, should this `var instrumentationKey = appConfig.GetValue<string>("APPINSIGHTS_INSTRUMENTATIONKEY");`' be better replaced by ` string connectionString = context.Configuration.GetValue<string>("APPLICATIONINSIGHTS_CONNECTION_STRING");` ?
> 
> Should this connectionString be preferrable kept in a Key vault, or is it sufficient keep it in e.g. for Web Api config connectionstring settings?

@HelenaCoppieters  Just an update, working on updating this here: https://github.com/Codit/fifa-worldcup-championship-predictions/pull/142

**Comment by stijnmoreels** [comment]
@HelenaCoppieters , can we close this issue?

**Comment by HelenaCoppieters** [comment]
ok
